// Shading entry point — reads G-buffer, builds ShadingContext, dispatches
// to the appropriate shading model, handles debug visualization modes.
//
// This file is concatenated after shade_common.wgsl and all shading model
// files by the CPU-side ShaderComposer.

// ---------- Shader Dispatch ----------
// GENERATED BY SHADER_COMPOSER — do not edit this function manually.
// The ShaderComposer replaces the SHADER_DISPATCH_PLACEHOLDER marker below
// with a generated switch statement over all registered shading models.

// SHADER_DISPATCH_PLACEHOLDER

// ---------- Entry point ----------

@compute @workgroup_size(8, 8, 1)
fn main(@builtin(global_invocation_id) pixel: vec3<u32>) {
    let dims = vec2<u32>(textureDimensions(hdr_output));
    if pixel.x >= dims.x || pixel.y >= dims.y {
        return;
    }

    let coord = vec2<i32>(pixel.xy);

    // Read G-buffer
    let pos_data = textureLoad(gbuf_position, coord, 0);
    let hit_dist = pos_data.w;

    let normal_data_raw = textureLoad(gbuf_normal, coord, 0);
    let motion_data_raw = textureLoad(gbuf_motion, coord, 0);

    // Sky pixel — analytic atmosphere or fallback gradient.
    if hit_dist >= MAX_FLOAT * 0.5 {
        var sky: vec3<f32>;
        if shade_uniforms.sky_params.z > 0.5 {
            let ray_dir = compute_view_ray(pixel.xy, dims);
            sky = atmosphere_sky(ray_dir, normalize(shade_uniforms.sun_dir.xyz));
        } else {
            let uv_y = f32(pixel.y) / f32(dims.y);
            sky = mix(SKY_HORIZON, SKY_ZENITH, uv_y);
        }

        textureStore(hdr_output, coord, vec4<f32>(sky, 1.0));
        return;
    }

    let world_pos = pos_data.xyz;
    var normal = normalize(normal_data_raw.xyz);

    let packed = textureLoad(gbuf_material, coord, 0);
    let material_id = packed.r & 0xFFFFu;
    let secondary_id = (packed.r >> 16u) & 0xFFFFu;
    let blend_weight_u8 = packed.g & 0xFFu;
    let object_id_bits = (packed.g >> 8u) & 0xFFu;

    // Resolve primary material from table.
    var resolved = resolve_material_from(materials[material_id]);

    // Material blending from G-buffer (sampled at exact hit point by ray march).
    let blend_weight = f32(blend_weight_u8) / 255.0;
    if blend_weight > 0.0 && secondary_id != material_id {
        let secondary = resolve_material_from(materials[secondary_id]);
        resolved = blend_resolved_materials(resolved, secondary, blend_weight);
    }

    // --- Glass transparency: the G-buffer surface IS the glass. ---
    // Handle the entire refraction pipeline here, then return early.
    if resolved.opacity < 1.0 {
        let view_dir = normalize(shade_uniforms.camera_pos.xyz - world_pos);
        let glass_n_dot_v = max(dot(normal, view_dir), 0.001);

        // Fresnel from IOR (Schlick approximation).
        // metallic on glass material acts as a "reflectivity boost" control.
        let f0_raw = dielectric_f0(resolved.ior);
        let f0 = mix(f0_raw, 0.5, resolved.metallic);
        let fresnel = f0 + (1.0 - f0) * pow(1.0 - glass_n_dot_v, 5.0);

        // Reflection: blend sharp sky reflection with blurred GI based on roughness.
        let reflect_dir = reflect(-view_dir, normal);
        var sharp_reflection: vec3<f32>;
        if shade_uniforms.sky_params.z > 0.5 {
            sharp_reflection = atmosphere_sky(reflect_dir, normalize(shade_uniforms.sun_dir.xyz));
        } else {
            let sky_up = clamp(reflect_dir.y * 0.5 + 0.5, 0.0, 1.0);
            sharp_reflection = mix(SKY_HORIZON, SKY_ZENITH, sky_up);
        }
        let jitter = fract(sin(dot(vec2<f32>(pixel.xy), vec2<f32>(12.9898, 78.233))) * 43758.5453);
        let gi_origin = world_pos + normal * SHADOW_BIAS * 2.0;
        let blurred_reflection = cone_trace_specular(gi_origin, reflect_dir, resolved.roughness, jitter);
        let blur_factor = smoothstep(0.0, 0.5, resolved.roughness);
        let reflection = mix(sharp_reflection, blurred_reflection * shade_uniforms.sun_color.w, blur_factor);

        // Direct specular highlight from lights (sun glare on glass).
        var glass_specular = vec3<f32>(0.0);
        let num_lights_g = shade_uniforms.num_lights;
        for (var gli = 0u; gli < num_lights_g; gli++) {
            let gl = lights[gli];
            if gl.light_type != LIGHT_TYPE_DIRECTIONAL { continue; }
            let gl_dir = normalize(vec3<f32>(gl.dir_x, gl.dir_y, gl.dir_z));
            let gl_radiance = vec3<f32>(gl.color_r, gl.color_g, gl.color_b) * gl.intensity;
            let gl_n_dot_l = max(dot(normal, gl_dir), 0.0);
            if gl_n_dot_l > 0.0 {
                let half_vec = normalize(view_dir + gl_dir);
                let gl_n_dot_h = max(dot(normal, half_vec), 0.0);
                let gl_h_dot_v = max(dot(half_vec, view_dir), 0.0);
                let r = max(resolved.roughness, 0.04);
                let d = distribution_ggx(gl_n_dot_h, r);
                let v = visibility_smith_ggx(glass_n_dot_v, gl_n_dot_l, r);
                let gl_f = f0 + (1.0 - f0) * pow(1.0 - gl_h_dot_v, 5.0);
                glass_specular += d * v * gl_f * gl_radiance * gl_n_dot_l;
            }
        }

        // Transmission: refract through glass interior, find what's behind.
        let transmission = (1.0 - fresnel) * (1.0 - resolved.opacity);
        var transmitted_color = vec3<f32>(0.0);

        if transmission > 0.01 {
            let incident = normalize(world_pos - shade_uniforms.camera_pos.xyz);

            // Step through transparent material by sampling voxel material IDs.
            // We can't use the object's SDF (march_glass_interior) because glass
            // shares an object with walls — the SDF includes non-glass geometry.
            // Instead, step along the ray checking the material at each voxel
            // until we exit transparent material.
            var exit_pos = world_pos;
            var path_through = 0.0;
            var found_glass_obj = false;
            var glass_obj_idx = 0u;
            if object_id_bits > 0u {
                for (var gi = 0u; gi < v2_scene.num_objects; gi = gi + 1u) {
                    if objects[gi].object_id == object_id_bits {
                        glass_obj_idx = gi;
                        found_glass_obj = true;
                        break;
                    }
                }
            }
            if found_glass_obj {
                let glass_obj = objects[glass_obj_idx];
                let vs = max(glass_obj.voxel_size, 0.01);
                let brick_extent = vs * 8.0;
                let dims = vec3<u32>(glass_obj.brick_map_dims_x, glass_obj.brick_map_dims_y, glass_obj.brick_map_dims_z);
                let grid_size = vec3<f32>(dims) * brick_extent;

                // Transform ray to object-local space.
                let local_origin = (glass_obj.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                let local_dir = normalize((glass_obj.inverse_world * vec4<f32>(incident, 0.0)).xyz);
                let safe_dir = select(local_dir, sign(local_dir) * vec3<f32>(1e-10), abs(local_dir) < vec3<f32>(1e-10));
                let inv_dir = 1.0 / safe_dir;

                var t_local = vs * 0.5;
                let max_t = brick_extent * f32(max(dims.x, max(dims.y, dims.z)));
                for (var si = 0u; si < 64u; si++) {
                    if t_local > max_t { break; }
                    let local_pos = local_origin + safe_dir * t_local;
                    let grid_pos = local_pos + grid_size * 0.5;
                    let brick_coord = vec3<i32>(floor(grid_pos / brick_extent));

                    // Out of grid → exited object.
                    if any(brick_coord < vec3<i32>(0)) || any(vec3<u32>(brick_coord) >= dims) {
                        break;
                    }

                    // Octree lookup for glass transparency ray.
                    let glass_extent = bitcast<f32>(glass_obj.brick_map_dims_y);
                    let glass_octree_pos = local_pos + vec3<f32>(glass_extent * 0.5);
                    let slot = octree_find_slot(glass_obj.brick_map_offset, glass_obj.brick_map_dims_x, glass_extent, glass_octree_pos);

                    if slot == EMPTY_SLOT {
                        // Exited object.
                        break;
                    }
                    if slot == INTERIOR_SLOT {
                        // Skip entire brick — still inside glass.
                        let brick_min = vec3<f32>(brick_coord) * brick_extent - grid_size * 0.5;
                        let brick_max = brick_min + vec3<f32>(brick_extent);
                        let t_exit = intersect_aabb(local_origin, inv_dir, brick_min, brick_max);
                        t_local = t_exit.y + vs * 0.1;
                        continue;
                    }

                    // Allocated brick: check opacity and material.
                    let opacity = sample_opacity_trilinear(local_pos, glass_obj);
                    if opacity < OPACITY_SURFACE_THRESHOLD {
                        // Exited object (opacity below surface threshold).
                        break;
                    }
                    // Check if we've hit opaque material within the glass object.
                    let mat_data = sample_voxelized_material_full(local_pos, glass_obj);
                    let probe_mat_id = u32(mat_data.x);
                    let probe_opacity = materials[probe_mat_id].opacity;
                    if probe_opacity >= 1.0 {
                        break;
                    }
                    t_local += vs * 0.5;
                }
                // Convert local t back to world-space distance.
                let world_scale = length((glass_obj.inverse_world * vec4<f32>(incident, 0.0)).xyz);
                path_through = t_local / max(world_scale, 1e-10);
                exit_pos = world_pos + incident * path_through;
            } else {
                path_through = 0.05;
                exit_pos = world_pos + incident * path_through;
            }

            // Trace behind the glass using the original incident direction
            // (thin glass: exit refraction cancels entry refraction).
            let view_behind = normalize(shade_uniforms.camera_pos.xyz - exit_pos);
            let behind = trace_and_shade_behind_glass(
                exit_pos, incident, 50.0, view_behind, jitter
            );

            let absorption = beer_absorption(resolved.albedo, path_through);
            if behind.hit {
                transmitted_color = behind.color * absorption;
            } else {
                var sky_behind: vec3<f32>;
                if shade_uniforms.sky_params.z > 0.5 {
                    sky_behind = atmosphere_sky(incident, normalize(shade_uniforms.sun_dir.xyz));
                } else {
                    let uv_y = clamp(incident.y * 0.5 + 0.5, 0.0, 1.0);
                    sky_behind = mix(SKY_HORIZON, SKY_ZENITH, uv_y);
                }
                transmitted_color = sky_behind * absorption;
            }
        }

        // Glass tint: opacity controls how much the glass absorbs/colors light
        let glass_tint = mix(vec3<f32>(1.0), resolved.albedo, resolved.opacity);

        // Composite: reflection + transmitted scene + specular highlights
        var color = reflection * fresnel + transmitted_color * glass_tint * transmission + glass_specular;

        // Debug modes still apply to glass
        color = apply_debug_mode(color, world_pos, normal, material_id, packed, pixel.xy);

        textureStore(hdr_output, coord, vec4<f32>(color, 1.0));
        return;
    }

    // --- Opaque surface shading ---

    // Per-voxel paint color.
    // Skinned objects: rest-pose color packed into motion.z (RGB24 as bitcast u32, 0 = none).
    // Non-skinned: sample the companion color pool.
    let skinned_color_u32 = bitcast<u32>(motion_data_raw.z);
    if skinned_color_u32 != 0u {
        let rgb_packed = skinned_color_u32;
        let r = f32((rgb_packed >> 16u) & 0xFFu) / 255.0;
        let g = f32((rgb_packed >> 8u) & 0xFFu) / 255.0;
        let b = f32(rgb_packed & 0xFFu) / 255.0;
        resolved.albedo = resolved.albedo * vec3<f32>(r, g, b);
    } else {
        // Read RGB565 color packed into bits 16-31 of material.g by the raster
        // fragment shader. This is the direct per-voxel color — no re-traversal needed.
        let color_rgb565 = (packed.g >> 16u) & 0xFFFFu;
        if color_rgb565 != 0u {
            let cr5 = color_rgb565 & 0x1Fu;
            let cg6 = (color_rgb565 >> 5u) & 0x3Fu;
            let cb5 = (color_rgb565 >> 11u) & 0x1Fu;
            let r = f32(cr5) / 31.0;
            let g = f32(cg6) / 63.0;
            let b = f32(cb5) / 31.0;
            resolved.albedo = resolved.albedo * vec3<f32>(r, g, b);
        }
    }
    var albedo = resolved.albedo;
    var roughness = clamp(resolved.roughness, 0.04, 1.0);
    let metallic = resolved.metallic;

    // Procedural noise variation
    if resolved.noise_channels != 0u && resolved.noise_scale > 0.0 && resolved.noise_strength > 0.0 {
        let noise_pos = world_pos * resolved.noise_scale;
        let n = simplex3d(noise_pos);
        let ns = n * resolved.noise_strength;

        if (resolved.noise_channels & NOISE_CHANNEL_ALBEDO) != 0u {
            albedo = clamp(albedo + albedo * ns, vec3<f32>(0.0), vec3<f32>(1.0));
        }
        if (resolved.noise_channels & NOISE_CHANNEL_ROUGHNESS) != 0u {
            roughness = clamp(roughness + ns * 0.5, 0.04, 1.0);
        }
        if (resolved.noise_channels & NOISE_CHANNEL_NORMAL) != 0u {
            // Tetrahedron trick: 4 evaluations instead of 6 for gradient estimation
            let eps = 0.01 / resolved.noise_scale;
            let k0 = vec3<f32>( 1.0, -1.0, -1.0);
            let k1 = vec3<f32>(-1.0, -1.0,  1.0);
            let k2 = vec3<f32>(-1.0,  1.0, -1.0);
            let k3 = vec3<f32>( 1.0,  1.0,  1.0);
            let bump = k0 * simplex3d(noise_pos + k0 * eps)
                     + k1 * simplex3d(noise_pos + k1 * eps)
                     + k2 * simplex3d(noise_pos + k2 * eps)
                     + k3 * simplex3d(noise_pos + k3 * eps);
            normal = normalize(normal + bump * resolved.noise_strength * 0.25);
        }
    }

    // F0: reflectance at normal incidence
    let f0 = mix(vec3<f32>(0.04), albedo, metallic);

    // View direction
    let view_dir = normalize(shade_uniforms.camera_pos.xyz - world_pos);
    let n_dot_v = max(dot(normal, view_dir), 0.001);

    // Use the per-voxel albedo (which includes voxel color) for SSS,
    // not the material's subsurface_color. Otherwise changing materials
    // overwrites the visual color via SSS contribution.
    let sss_color = albedo;

    // Atmospheric shadow softening at distance
    let cam_dist = length(world_pos - shade_uniforms.camera_pos.xyz);
    let atmo_shadow_fill = (1.0 - exp(-shade_uniforms.shadow_params.w * cam_dist)) * SHADOW_ATMO_MAX_FILL;

    // Per-pixel jitter to break cone tracing banding.
    let jitter = fract(sin(dot(vec2<f32>(pixel.xy), vec2<f32>(12.9898, 78.233))) * 43758.5453);

    // Contact shadow placeholder — not yet implemented.
    let contact = 1.0;

    let reflect_dir = reflect(-view_dir, normal);

    // Build ShadingContext
    let ctx = ShadingContext(
        world_pos,
        normal,
        view_dir,
        n_dot_v,
        albedo,
        roughness,
        metallic,
        resolved.emission,
        resolved.emission_strength,
        resolved.subsurface,
        resolved.subsurface_color,
        resolved.opacity,
        resolved.ior,
        f0,
        reflect_dir,
        cam_dist,
        jitter,
        contact,
        atmo_shadow_fill,
        pixel.xy,
        material_id,
        sss_color,
    );

    // Dispatch to shading model based on shader_id (from material table).
    // When blending two materials, use the dominant material's shader model.
    let primary_shader_id = materials[material_id].shader_id;
    let secondary_shader_id = materials[secondary_id].shader_id;
    var shader_id = primary_shader_id;
    if blend_weight > 0.5 && secondary_id != material_id {
        shader_id = secondary_shader_id;
    }
    var color = dispatch_shade(shader_id, ctx);

    // Debug visualization modes
    color = apply_debug_mode(color, world_pos, normal, material_id, packed, pixel.xy);

    // Brush overlay cursor ring — Euclidean distance from brush center in local space.
    // The G-buffer only contains surface pixels, so the ring naturally clips at edges.
    if brush_overlay.brush_active != 0u && object_id_bits > 0u {
        for (var oi_b = 0u; oi_b < v2_scene.num_objects; oi_b = oi_b + 1u) {
            let obj_b = objects[oi_b];
            if obj_b.object_id == brush_overlay.brush_object_id && (obj_b.geom_type == GEOM_TYPE_VOXELIZED || obj_b.geom_type == GEOM_TYPE_PROCEDURAL) {
                let local_pos_b = (obj_b.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                let diff = local_pos_b - brush_overlay.brush_center_local.xyz;
                // Scale-aware distance (account for non-uniform object scale).
                let scale = vec3<f32>(obj_b.accumulated_scale_x, obj_b.accumulated_scale_y, obj_b.accumulated_scale_z);
                let dist = length(diff * scale);

                let radius = brush_overlay.brush_radius;
                let falloff_frac = brush_overlay.brush_falloff;

                // Only draw within a reasonable range of the brush.
                if dist < radius * 1.5 {
                    // Outer ring: at brush_radius
                    let ring_width = radius * 0.04;
                    let outer_t = abs(dist - radius) / ring_width;
                    let outer_ring = 1.0 - smoothstep(0.0, 1.0, outer_t);

                    // Inner ring: at core radius (falloff boundary)
                    var inner_ring = 0.0;
                    if falloff_frac > 0.01 {
                        let core_radius = radius * (1.0 - falloff_frac);
                        let inner_t = abs(dist - core_radius) / ring_width;
                        inner_ring = (1.0 - smoothstep(0.0, 1.0, inner_t)) * 0.4;
                    }

                    let ring_alpha = max(outer_ring, inner_ring);
                    if ring_alpha > 0.01 {
                        let ring_col = brush_overlay.brush_color.rgb;
                        color = mix(color, ring_col, ring_alpha * brush_overlay.brush_color.a);
                    }
                }
                break;
            }
        }
    }

    textureStore(hdr_output, coord, vec4<f32>(color, 1.0));
}

// ---------- Debug Mode Helper ----------

fn apply_debug_mode(
    shaded_color: vec3<f32>,
    world_pos: vec3<f32>,
    normal: vec3<f32>,
    material_id: u32,
    packed: vec4<u32>,
    pixel: vec2<u32>,
) -> vec3<f32> {
    var color = shaded_color;
    switch shade_uniforms.debug_mode {
        case 1u: {
            color = normal * 0.5 + 0.5;
        }
        case 2u: {
            color = abs(world_pos) * 0.5;
        }
        case 3u: {
            let mid = material_id;
            color = vec3<f32>(
                f32((mid * 7u + 3u) % 11u) / 10.0,
                f32((mid * 13u + 5u) % 11u) / 10.0,
                f32((mid * 19u + 7u) % 11u) / 10.0,
            );
        }
        case 4u: {
            // Diffuse-only: approximate
            color = vec3<f32>(0.5);
        }
        case 5u: {
            // Specular-only: approximate
            color = vec3<f32>(0.04);
        }
        case 6u: {
            // GI only — indirect diffuse + specular, no direct lighting
            let ao = opacity_ao(world_pos + normal * SHADOW_BIAS, normal);
            let gi_origin = world_pos + normal * SHADOW_BIAS * 2.0;
            let jitter = fract(sin(dot(vec2<f32>(pixel), vec2<f32>(12.9898, 78.233))) * 43758.5453);
            let gi_diffuse_raw = cone_trace_diffuse(gi_origin, normal, jitter);
            let gi_diffuse = gi_diffuse_raw * ao * shade_uniforms.sun_color.w;
            let reflect_dir = reflect(-normalize(shade_uniforms.camera_pos.xyz - world_pos), normal);
            let gi_specular_raw = cone_trace_specular(gi_origin, reflect_dir, 0.5, jitter);
            let gi_specular = gi_specular_raw * ao * shade_uniforms.sun_color.w;
            color = gi_diffuse + gi_specular;
        }
        case 7u: {
            // SDF distance visualization: blue (inside) → white (surface) → red (outside)
            let motion_data = textureLoad(gbuf_motion, vec2<i32>(pixel), 0);
            let sdf_d = motion_data.w;
            let scale = 10.0;
            let t7 = clamp(sdf_d * scale, -1.0, 1.0);
            if t7 < 0.0 {
                color = mix(vec3<f32>(1.0), vec3<f32>(0.0, 0.0, 1.0), -t7);
            } else {
                color = mix(vec3<f32>(1.0), vec3<f32>(1.0, 0.0, 0.0), t7);
            }
        }
        case 8u: {
            // Brick boundary overlay with hash-colored bricks and voxel sub-grid
            let obj_id8 = (packed.g >> 8u) & 0xFFu;
            var found_obj8 = false;
            var obj8_idx = 0u;
            for (var oi8 = 0u; oi8 < v2_scene.num_objects; oi8 = oi8 + 1u) {
                if objects[oi8].object_id == obj_id8 {
                    obj8_idx = oi8;
                    found_obj8 = true;
                    break;
                }
            }
            if found_obj8 {
                let obj = objects[obj8_idx];
                let local_pos = (obj.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                let vs = obj.voxel_size;
                let grid_size = vec3<f32>(f32(obj.brick_map_dims_x), f32(obj.brick_map_dims_y), f32(obj.brick_map_dims_z)) * vs * 8.0;
                let grid_pos = local_pos + grid_size * 0.5;
                let voxel_coord = grid_pos / vs;
                let brick_coord = vec3<u32>(floor(voxel_coord / 8.0));
                let local_voxel = fract(voxel_coord / 8.0) * 8.0;

                // Brick boundary detection
                let edge_dist = min(local_voxel, vec3<f32>(8.0) - local_voxel);
                let min_edge = min(edge_dist.x, min(edge_dist.y, edge_dist.z));
                let on_brick_edge = 1.0 - smoothstep(0.2, 0.5, min_edge);

                // Voxel sub-grid (faint lines)
                let vf = fract(voxel_coord);
                let ve = min(vf, vec3<f32>(1.0) - vf);
                let on_voxel = (1.0 - smoothstep(0.1, 0.2, min(ve.x, min(ve.y, ve.z)))) * 0.2;

                // Hash brick coordinate for a unique color per brick
                let h = brick_coord.x * 73u + brick_coord.y * 157u + brick_coord.z * 311u;
                let bc = vec3<f32>(
                    f32((h * 13u + 7u) % 256u) / 255.0,
                    f32((h * 29u + 11u) % 256u) / 255.0,
                    f32((h * 43u + 17u) % 256u) / 255.0
                ) * 0.5 + 0.25;

                color = mix(bc, vec3<f32>(1.0, 1.0, 0.0), on_brick_edge);
                color = mix(color, vec3<f32>(0.6), on_voxel);
            } else {
                color = normal * 0.5 + 0.5;
            }
        }
        case 9u: {
            // Cloud shadow transmittance: white = fully lit, black = fully shadowed
            let cloud_t = textureLoad(shadow_ao_tex, vec2<i32>(pixel), 0).b;
            color = vec3<f32>(cloud_t);
        }
        case 10u: {
            // Bone weight visualization placeholder.
            let bone_placeholder = f32(packed.r & 0xFFu) / 255.0;
            color = vec3<f32>(bone_placeholder, 0.2, 1.0 - bone_placeholder);
        }
        case 11u: {
            // Raw per-voxel color debug — shows color companion map data directly.
            let obj_id_dbg = (packed.g >> 8u) & 0xFFu;
            var found_dbg = false;
            for (var oi_dbg = 0u; oi_dbg < v2_scene.num_objects; oi_dbg = oi_dbg + 1u) {
                let obj_dbg = objects[oi_dbg];
                if obj_dbg.object_id == obj_id_dbg && (obj_dbg.geom_type == GEOM_TYPE_VOXELIZED || obj_dbg.geom_type == GEOM_TYPE_PROCEDURAL) {
                    if obj_dbg.is_skinned == 0u {
                        let lp = (obj_dbg.inverse_world * vec4<f32>(world_pos, 1.0)).xyz;
                        let paint = sample_voxelized_color(lp, obj_dbg);
                        if paint.a > 0.0 {
                            color = paint.rgb;
                            found_dbg = true;
                        } else {
                            color = vec3<f32>(1.0, 0.0, 1.0); // magenta = no color data
                        }
                    }
                    break;
                }
            }
            if !found_dbg {
                color = vec3<f32>(0.0, 0.0, 0.0); // black = no object found
            }
        }
        case 12u: {
            // Raw shadow (R) — white = fully lit, black = fully shadowed.
            let sa = textureLoad(shadow_ao_tex, vec2<i32>(pixel), 0);
            color = vec3<f32>(sa.r);
        }
        case 13u: {
            // Raw AO (G) — white = no occlusion, black = fully occluded.
            let sa = textureLoad(shadow_ao_tex, vec2<i32>(pixel), 0);
            color = vec3<f32>(sa.g);
        }
        default: {
            // Normal shading (already computed)
        }
    }
    return color;
}
